- hosts: master
  become: yes
  gather_facts: false
  tasks:
  - name: get join command
    shell: kubeadm token create --print-join-command
    register: join_command_raw
 
  - name: set join command
    set_fact:
      join_command: "{{ join_command_raw.stdout_lines[0] }}"
 
- hosts: node
  become: yes
  tasks:
  - name: remove swap
    shell: "swapoff -a"
 
  - name: join cluster	
    shell: "{{ hostvars[groups['master'][0]].join_command }} >> node_joined.txt"
    args:
      chdir: $HOME
      creates: node_joined.txt

- hosts: master
  become: yes  
  tasks:
    - name: copy kubeadm kube-config to local
      fetch:
        src: /etc/kubernetes/admin.conf
        dest: ./kubeconfig/
        flat: yes
