---
- name: Terminate Instances
  ec2_instance_info:
    region: "{{ region_name }}"
  register: ec2_info
 
- name: displaying output
  debug: msg="{{item.instance_id}}"
  with_items: "{{ec2_info.instances}}"
 
- name: terminate
  ec2:
    instance_ids: "{{item.instance_id}}"
    region: "{{ region_name }}"
    state: absent
    wait: yes
  with_items: "{{ec2_info.instances}}"
